## Урок 3. Линейные преобразования

In [2]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

__1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей__ $A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}$

Сначала нужно найти собственные значения линейного оператора:

$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix}=0$

$(-1-\lambda)(6-\lambda)-(-6\cdot 2)=0$

$\lambda^2-5\lambda+6=0$

$\lambda_1=3,\,\,\, \lambda_2=2$

Собственные векторы:  
* для $\lambda_1=3$

$\begin{pmatrix}
-1-3 & -6\\ 
2 & 6-3
\end{pmatrix}=\begin{pmatrix}
-4 & -6\\ 
2 & 3
\end{pmatrix}$

Первая строка линейно зависима от второй строки, значит ее можно вычеркнуть. Получается:  
$2x_1+3x_2=0\,\,\, \Rightarrow\,\,\, x_1=-1.5 x_2$

Первый собственный вектор равен $(-1.5 x_2, x_2)$
* для $\lambda_2=2$  

$\begin{pmatrix}
-1-2 & -6\\ 
2 & 6-2
\end{pmatrix}=\begin{pmatrix}
-3 & -6\\ 
2 & 4
\end{pmatrix}$

Первая строка также линейно зависима от второй строки, поэтому её тоже вычеркиваем. Получается:  
$2x_1+4x_2=0\,\,\, \Rightarrow\,\,\, x_1=-2 x_2$

Второй собственный вектор равен $(-2 x_2, x_2)$

In [3]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


__2. Дан оператор поворота на 180 градусов, задаваемый матрицей__ $A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}$

Показать, что __любой__ вектор является для него собственным.

Находим собственные значения линейного оператора:  

$\begin{vmatrix}
-1 & 0\\ 
0 & -1
\end{vmatrix}=0$

$(-1-\lambda)^2-0=0$

$\lambda=-1$

Находим собственный вектор, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$: 

$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
-1
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$

$\begin{cases}
-x_1=-x_1, \\
-x_2=-x_2
\end{cases}\,\,\, \Rightarrow\,\,\,
\begin{cases}
x_1=x_1, \\
x_2=x_2
\end{cases}$

Проверяем при помощи поиска собственного вектора способом из первого задания:  

$\begin{pmatrix}
-1-(-1) & 0\\ 
0 & -1-(-1)
\end{pmatrix}=
\begin{pmatrix}
0 & 0\\ 
0 & 0
\end{pmatrix}$

Так как $x_1$ и $x_2$ могут принимать любые значения $\Rightarrow$ для данного оператора поворота любой вектор является собственным.

In [5]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


__3. Пусть линейный оператор задан матрицей__ $A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1 \\ 
1
\end{pmatrix}=\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}$

$\begin{cases}
1+1=\lambda \cdot 1, \\
-1+3=\lambda \cdot 1
\end{cases}\,\,\, \Rightarrow\,\,\,
\begin{cases}
\lambda=2, \\
\lambda=2
\end{cases}$

Следовательно вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение составляет $\lambda=2$.

In [6]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]


__4. Пусть линейный оператор задан матрицей__ $A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\ 
0 & 0 & 3 
\end{pmatrix}$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\ 
0 & 0 & 3 
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\ 
-4 
\end{pmatrix}=\lambda
\begin{pmatrix}
3\\ 
-3\\ 
-4 
\end{pmatrix}$

$\begin{cases}
-9=3\lambda, \\
9=-3\lambda, \\
-12=-4\lambda
\end{cases}\,\,\, \Rightarrow\,\,\,
\begin{cases}
\lambda=-3, \\
\lambda=-3, \\
\lambda=3
\end{cases}$

Следовательно такая система не имеет смысла. Следовательно вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.

In [7]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
