## Урок 5. Сингулярное разложение матриц

__1. Найти с помощью NumPy SVD для матрицы__ $\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}$

In [27]:
import numpy as np
from numpy.linalg import norm
np.set_printoptions(precision=2, suppress=True)

In [28]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [29]:
U, s, W = np.linalg.svd(A)

V = W.T # Транспонируем матрицу W

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [30]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [31]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [32]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [33]:
print(f'Проверка:\n{np.dot(np.dot(U, D), V.T)}')

Проверка:
[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


__2. Для матрицы из предыдущего задания найти:__

In [34]:
# а) евклидову норму;
print(f'Самое большое собственное значение: \n{s[0]}\n')
print(f'l1 норма вектора D:\n{norm(D, ord=2)}')


Самое большое собственное значение: 
8.824868854820444

l1 норма вектора D:
8.824868854820444


In [35]:
# б) норму Фробениуса
np.sqrt(np.sum(D**2))

11.045361017187263